#!/bin/bash 

# openifclosed APPLICATION
# If the application is already running, this command focuses the application 
# window. If it is closed, it starts the application.
# Requires wmcrtl

application=$1

window_id=$(wmctrl -l -p -x | grep --ignore-case $application | cut -d ' ' -f1 | head -n 1)

if [[ $window_id == "" ]]; then
    $application
else
    wmctrl -i -a $window_id
fi
