#!/bin/bash 

# openifclosed APPLICATION
# If the application is already running, this command focuses the application 
# window. If it is closed, it starts the application.

window_id=$(wmctrl -l -p -x | grep --ignore-case $1 | cut -d ' ' -f1 | head -n 1)

if [[ $window_id == "" ]]; then
    $1
else
    wmctrl -i -a $window_id
fi
