#!/bin/bash 

# openifclosed APPLICATION
# If the application is already running, this command focuses the application 
# window. If it is closed, it starts the application.
  
output=$(wmctrl -a $1 -v 2>&1) 
 
if [[ $output != *"Using window"* ]]; then 
    $1 
fi 
